services:
  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 1147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://admin:admin@rabbit:5672//
      - RESULT_BACKEND=rpc://
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - rabbit

  worker:
    build: .
    # command: celery -A app.celery_app.celery_app worker --loglevel=info -Q celery --logfile=/app/celery.log
    # volumes:
    #   - ./app:/app/
    env_file:
      - ./.env
    depends_on:
      - rabbit
    # environment:
    #   - C_FORCE_ROOT=yes
